### ISSUE TITLE
Mod conflict with MagicBuilder

### ISSUE THREAD

**Issue by DiZeroX** [hocha113/CalamityOverhaul#3]
I understand if this issue is not feasible to be fixed and this issue can be closed.

~~After February 19th update that implemented these changes:~~ I think it's actually one of the February 17th updates. (A way to install older versions would be nice, so I can figure out which update caused it)

[MagicBuilder](https://steamcommunity.com/sharedfiles/filedetails/?id=3024322683&searchtext=magicBuilder) mod can no longer be reloaded in TModLoader. ~~I'm guessing due to the `Great Overhaul Codex`?~~

Here is the error message:

```
[04:45:30.557] [.NET ThreadPool Worker/INFO] [tML]: Adding Recipes...
[04:45:30.696] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading MagicBuilder v1.2
It has been detected that this mod was built for tModLoader v2023.6.25.31
However, you are using tModLoader v2023.12.3.1
The mod(s) have been automatically disabled.
Terraria.ModLoader.Exceptions.MultipleException: Multiple errors occurred.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53
   --- End of inner exception stack trace ---
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 65
   at Terraria.ModLoader.RecipeLoader.AddRecipes() in tModLoader\Terraria\ModLoader\RecipeLoader.cs:line 47
   at Terraria.Recipe.SetupRecipes() in tModLoader\Terraria\Recipe.cs:line 14631
   at Terraria.ModLoader.ModContent.SetupRecipes(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 425
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 348
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 127
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #3) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #4) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #5) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #6) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #7) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #8) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #9) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #10) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #11) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #12) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #13) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #14) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #15) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #16) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #17) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #18) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #19) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #20) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #21) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #22) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #23) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #24) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #25) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #26) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #27) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #28) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #29) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #30) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #31) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #32) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #33) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #34) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #35) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #36) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #37) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #38) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #39) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #40) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #41) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #42) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #43) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #44) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #45) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #46) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

 ---> (Inner Exception #47) System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicBuilder.Items.Item.AddRecipes() in MagicBuilder\Base\Item.cs:line 37
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 53<---

[04:45:30.716] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: MagicBuilder

```
[Full log file: client.log](https://github.com/hocha113/CalamityOverhaul/files/14357586/client.log)

**Comment by hocha113** [comment]
Oh? What mod is that? I remember some players mentioning it. Well, I'll check the error logs and try to adapt the mod MagicBuilder

**Comment by DiZeroX** [comment]
It's a fairly popular mod that adds consumable items that generate houses and structures with the same aesthetic as the biome it's in. 

Here is workshop link: https://steamcommunity.com/sharedfiles/filedetails/?id=3024322683

The error is reproducible by only enabling Magic Builder and Calamity/Calamity Overhaul. Enabling only Magic Builder and Calamity (without Overhaul) does not result in an error. 

If Overhaul could be adapted, that would be great.

**Comment by hocha113** [comment]
This issue should have been fixed. Check out the Creative Workshop's updated version 0.342!
Quoting the changelog from the Creative Workshop:
1. Fixed a critical issue where the mod couldn't load when Magic Builder was enabled.
2. Addressed a severe problem causing game crashes when using Magic Store with certain items.
3. Resolved an issue with abnormal item icon rendering for Murasama in certain situations.
4. Blighted Cleaver: Reduced the number of scythes generated after hitting enemies from 5 to 1. The chance to spawn Jungle Scythes on true melee hits against worm-type enemies is now 1/5.
5. Defiled Greatsword: The chance to spawn Jungle Scythes on true melee hits against worm-type enemies is now 1/3.
6. The Last Mourning: Fearful Skulls now deal 33% of weapon panel damage, and additional Inferno Spirits deal 1x weapon damage. The spawn probability for Inferno Spirits has been reduced from 50% to 33%.
7. Slightly reduced the recoil of Mini Sharks and Megasharks.
8. Further balanced Murasama's mechanics, addressing potential issues. Significantly increased the damage of the downward strike skill to prevent potential boss insta-kills. 
The Rising Dragon Slash will now benefit more from melee damage bonuses, slightly reduced cooldown, and smoothed out damage coefficients for different bosses across phases.
9. Added "Camera Easing" setting, enabled by default, providing a more natural and smooth experience for long-distance dashes.
10. Slightly optimized the multiplayer mod for an improved gaming experience.

**Comment by DiZeroX** [comment]
Thanks!
