### ISSUE TITLE
Terraria.ModLoader.Exceptions.JITException

### ISSUE THREAD

**Issue by bp82125** [hocha113/CalamityOverhaul#5]
Hi, today I had a fresh install of this mod with some of other calamity mods and I got this issue:

Terraria.ModLoader.Exceptions.JITException: 
In CalamityAmmo.Misc.QianXing+<>c.<AddShops>b__13_0, Could not load type 'CalamityMod.BiomeManagers.AbovegroundAstralBiome' from assembly 'CalamityMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Terraria.ModLoader.Core.AssemblyManager.JITAssembliesAsync(IEnumerable 1 assemblies, PreJITFilter filter, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 419
   at Terraria.ModLoader.ModContent.JITModsAsync(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 384
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 311
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 132

Here's the full log: https://gist.github.com/bp82125/867b4990114abe6e512e55742dc03d22

**Comment by bp82125** [comment]
So I just tried to do the binary search debugging and found that the Wulfrum Alligator Mod, Calamity Ranger Expansion and Calamitous Journeys caused this. I disabled them and the game loaded properly again. I'm really sorry for wasting your time on this.
